---
- name: force_reset_playbook
  ansible.builtin.import_playbook: ../reset.yml
- name: pre_playbook
  ansible.builtin.import_playbook: ../pre_playbook.yml
- name: Scale the cluster
  ansible.builtin.import_playbook: playbooks/scale.yml
