---
- name: prepare for using kubespray playbook
  hosts: "{{ node | default('k8s_cluster') }}"
  become: true
  tasks:
    - name: Ensure the /etc/hosts file contains the required entry
      lineinfile:
        path: /etc/hosts
        line: "{{registry_host_ip}} {{registry_host}}"
        state: present
        backup: yes
      tags:
        - hosts_update

    - name: Ensure /etc/resolv.conf exists
      file:
        path: /etc/resolv.conf
        state: touch

    - name: Check the OS
      command: grep '^NAME=' /etc/os-release
      register: os_name_output

    - name: Set OS version variable 
      set_fact:
        is_openeuler: "{{ os_name_output.stdout | regex_search('openEuler', ignorecase=True) }}"
        is_rocky: "{{ os_name_output.stdout | regex_search('Rocky', ignorecase=True) }}"
        is_ubuntu: "{{ os_name_output.stdout | regex_search('Ubuntu', ignorecase=True) }}"
        is_centos: "{{ os_name_output.stdout | regex_search('CentOS', ignorecase=True) }}"
    
    # - name: Check if the node cache dir exists
    #   ansible.builtin.stat:
    #     path: "{{ node_repo_path }}"
    #   register: node_repo_stat
    
    # - name: Remove the node cache dir if it exists
    #   ansible.builtin.file:
    #     path: "{{ node_repo_path }}"
    #     state: absent
    #   when: node_repo_stat.stat.exists and node_repo_stat.stat.isreg
    - name: Remove the node cache dir if it exists
      ansible.builtin.command:
        cmd: rm -rf {{ node_repo_path }}

    - name: Ensure the node cache directory exists and set permissions to 777
      ansible.builtin.file:
        path: "{{ node_repo_path }}"
        state: directory
        mode: '0777'
        owner: "{{ ansible_user }}"
    
    - name: Check if tar is exists
      ansible.builtin.command:
        cmd: tar --version
      register: tar_version
      ignore_errors: true
      
    # 此处需要将rpm包名字写入config.yml
    - name: Copy tar rpm file from localhost to nodes (openEuler)
      ansible.builtin.copy:
        src: "{{ localhost_repo_path }}/{{ openEuler_tar_name }}"
        dest: "{{ node_repo_path }}"
      # timeout: 5
      # retries: 3
      # delay: 3
      when: is_openeuler and tar_version.rc != 0

    - name: Install tar using tar rpm (openEuler)
      command: rpm -ivh {{ node_repo_path }}/{{ openEuler_tar_name }}
      when: is_openeuler and tar_version.rc != 0

    # 规避使用rsync，因为目标主机上可能没有
    - name: Copy repo file from localhost to nodes (Rocky)
      ansible.builtin.copy:
        src: "{{ Rocky_repo_path }}"
        dest: "{{ node_repo_path }}"
      # timeout: 5
      # retries: 3
      # delay: 3
      when: is_rocky

    - name: Get repo tar filename (Rocky)
      set_fact:
        repo_tar_name: "{{ Rocky_repo_path.split('/') | last }}"
      when: is_rocky

    - name: Copy repo file from localhost to nodes (openEuler)
      ansible.builtin.copy:
        src: "{{ openEuler_repo_path }}"
        dest: "{{ node_repo_path }}"
      # timeout: 5
      # retries: 3
      # delay: 3
      when: is_openeuler

    - name: Get repo tar filename (openEuler)
      set_fact:
        repo_tar_name: "{{ openEuler_repo_path.split('/') | last }}"
      when: is_openeuler
      
    - name: Copy repo file from localhost to nodes (Centos)
      ansible.builtin.copy:
        src: "{{ Centos_repo_path }}"
        dest: "{{ node_repo_path }}"
      # timeout: 5
      # retries: 3
      # delay: 3
      when: is_centos

    - name: Get repo tar filename (Centos)
      set_fact:
        repo_tar_name: "{{ Centos_repo_path.split('/') | last }}"
      when: is_centos

    - name: Copy repo file from localhost to nodes (Ubuntu)
      ansible.builtin.copy:
        src: "{{ Ubuntu_repo_path }}"
        dest: "{{ node_repo_path }}"
      # timeout: 5
      # retries: 3
      # delay: 3
      when: is_ubuntu

    - name: Get repo tar filename (Ubuntu)
      set_fact:
        repo_tar_name: "{{ Ubuntu_repo_path.split('/') | last }}"
      when: is_ubuntu

    - name: Unarchive repo tar file
      unarchive:
        src: "{{ node_repo_path }}/{{repo_tar_name}}"
        dest: "{{ node_repo_path }}"
        remote_src: yes 

    - name: Set repo_name without tar
      set_fact:
        repo_name: "{{ repo_tar_name | regex_replace('\\.tar$', '') }}" 

    - name: Remove already exist repo dir
      command: rm -rf  {{ node_repo_path }}/repo
      ignore_errors: true

    - name: Move repo dir to target and rename directory
      command: mv {{ node_repo_path }}/{{repo_name}} {{ node_repo_path }}/repo
      ignore_errors: true

    - name: Find all .repo files(RedHat OS)
      find:
        paths: /etc/yum.repos.d
        patterns: "*.repo"
      register: repo_files
      when: not is_ubuntu

    - name: Backup exists .repo files(RedHat OS)
      command: mv {{ item.path }} {{ item.path }}.bak
      with_items: "{{ repo_files.files }}"
      when: 
        - repo_files.matched > 0
      when: not is_ubuntu

    - name: Create local-repo.repo in /etc/yum.repos.d (RedHat OS) 
      copy:
        dest: /etc/yum.repos.d/local-repo.repo
        content: |
          [local-repo]
          name=Local Repository
          baseurl=file://{{node_repo_path}}/repo
          enabled=1
          gpgcheck=0
      when: not is_ubuntu

    - name: Clean all yum caches (RedHat OS) 
      ansible.builtin.command:
        cmd: yum clean all
      become: yes
      when: not is_ubuntu

    - name: Rebuild yum cache (RedHat OS) 
      ansible.builtin.command:
        cmd: yum makecache
      become: yes
      when: not is_ubuntu

    - name: Backup exists .list files(Debian OS)
      command: mv /etc/apt/sources.list /etc/apt/sources.list.bak
      when: is_ubuntu

    - name: Create sources.list in /etc/apt (Debian OS) 
      copy:
        dest: /etc/apt/sources.list
        content: deb [trusted=yes] file:{{ node_repo_path }}/repo ./ 
      when: is_ubuntu

    - name: apt-get update (Debian OS) 
      ansible.builtin.command:
        cmd: apt-get update
      become: yes
      when: is_ubuntu

    - name: Install libselinux-python3 if OS is openEuler
      yum:
        name: libselinux-python3
        state: present
      when: is_openeuler

    - name: Install nfs-utils (Rocky or openEuler)
      yum:
        name: nfs-utils
        state: present
        allowerasing: true
      become: yes
      when: is_rocky or is_openeuler

    - name: Stop firewalld (RedHat OS)
      ansible.builtin.command:
        cmd: sudo systemctl stop firewalld
      become: yes
      when: not is_ubuntu
    
    - name: Stop ufw (Debian OS)
      ansible.builtin.command:
        cmd: sudo ufw disable
      become: yes
      when: is_ubuntu




